####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-grid
Description: DUNE module supporting grids in a corner-point format
Version: 2023.10-pre
Label: 2023.10-pre
Maintainer: atgeirr@sintef.no
MaintainerName: Atgeirr F. Rasmussen
Url: http://opm-project.org
Depends: dune-common (>= 2.7) dune-geometry (>= 2.7) dune-grid (>= 2.7) opm-common
Suggests: dune-istl (>= 2.7)
