.TH GRDECL2VTU "1" "April 2022" "grdecl2vtu 2022.04" "User Commands"
.SH NAME
grdecl2vtu \- Converter from Eclipse data files to Paraview files
.SH SYNOPSIS
.B grdecl2vtu
\fI\,filename.grdecl\/\fR
.SH DESCRIPTION
Converts the grid, porosity, and permeability data from an Eclipse data
file and creates a Paraview (*.vtu) that enables visualizing the data
with Paraview. The output will be stored in file filename.vtu.
