.TH MIRROR_GRID "1" "October 2024" "mirror_grid" "User Commands"
.SH NAME
mirror_grid \- Mirror the grid in one direction.
.SH SYNOPSIS
.B mirror_grid
\fI\,filename.grdecl\/\fR
\fI\,direction\/\fR
.SH DESCRIPTION
Parses the eclipse file filename.grdecl, mirrors the grid together
with the data in one direction and stores the result in file
filename-mirrored-direction.gdecl. Direction can either be x or y.
